import 'package:flutter/material.dart';
import '../core/models/food.dart';
import '../core/nutrition/nutrition_calculator.dart';
import '../data/repositories/fitlife_storage.dart';

const bg=Color(0xFFF7F9FB), blue=Color(0xFF3F6F9F), blueLight=Color(0xFFE8F0F7), green=Color(0xFF5BAF78), orange=Color(0xFFF3A33B), pink=Color(0xFFD85A9B), muted=Color(0xFF7B858E);

class FitLifeApp extends StatelessWidget{const FitLifeApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'FitLife',theme:ThemeData(useMaterial3:true,scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:blue)),home:const FitLifeShell());}
class FitLifeShell extends StatefulWidget{const FitLifeShell({super.key});@override State<FitLifeShell> createState()=>_FitLifeState();}
class _FitLifeState extends State<FitLifeShell>{
 final store=const FitLifeStorage(); int tab=0; DateTime day=DateTime.now(); bool loaded=false;
 double weight=104.2,start=110,goal=85; int age=36,height=175,water=0; String sex='Мужской'; double activity=1.2;
 final meals=<FoodEntry>[]; final weights=<WeightEntry>[];
 static String key(DateTime d)=>'${d.year}-${d.month.toString().padLeft(2,'0')}-${d.day.toString().padLeft(2,'0')}';
 List<FoodEntry> get today=>meals.where((e)=>e.dateKey==key(day)).toList(); int get kcal=>today.fold(0,(s,e)=>s+e.kcal); double get protein=>today.fold(0.0,(s,e)=>s+e.protein),fat=>today.fold(0.0,(s,e)=>s+e.fat),carbs=>today.fold(0.0,(s,e)=>s+e.carbs),fiber=>today.fold(0.0,(s,e)=>s+e.fiber);
 NutritionGoals get g=>const NutritionCalculator().calculate(weight:weight,height:height,age:age,sex:sex,activity:activity);
 double get progress{final t=start-goal;return t<=0?0:((start-weight)/t).clamp(0.0,1.0).toDouble();}
 @override void initState(){super.initState();load();}
 Future<void> load()async{final w=await store.readDouble('weight'),s=await store.readDouble('startWeight'),go=await store.readDouble('goalWeight'),a=await store.readInt('age'),h=await store.readInt('height'),wa=await store.readInt('water'),sx=await store.readString('sex');final mr=await store.readList('meals'),wr=await store.readList('weights');if(!mounted)return;setState((){if(w!=null)weight=w;if(s!=null)start=s;if(go!=null)goal=go;if(a!=null)age=a;if(h!=null)height=h;if(wa!=null)water=wa;if(sx!=null)sex=sx;meals..clear()..addAll(mr.map(FoodEntry.fromJson).whereType<FoodEntry>());weights..clear()..addAll(wr.map(WeightEntry.fromJson).whereType<WeightEntry>());loaded=true;});}
 Future<void> save()async{await store.writeDouble('weight',weight);await store.writeDouble('startWeight',start);await store.writeDouble('goalWeight',goal);await store.writeInt('age',age);await store.writeInt('height',height);await store.writeInt('water',water);await store.writeString('sex',sex);await store.writeList('meals',meals.map((e)=>e.toJson()).toList());await store.writeList('weights',weights.map((e)=>e.toJson()).toList());}
 void change(VoidCallback f){setState(f);save();}
 @override Widget build(BuildContext c){if(!loaded)return const Scaffold(body:Center(child:CircularProgressIndicator()));final pages=[home(),nutrition(),weightPage(),stats(),profile()];return Scaffold(body:SafeArea(child:pages[tab]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),indicatorColor:blueLight,destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Сегодня'),NavigationDestination(icon:Icon(Icons.restaurant_outlined),selectedIcon:Icon(Icons.restaurant),label:'Питание'),NavigationDestination(icon:Icon(Icons.monitor_weight_outlined),selectedIcon:Icon(Icons.monitor_weight),label:'Вес'),NavigationDestination(icon:Icon(Icons.insights_outlined),selectedIcon:Icon(Icons.insights),label:'Статистика'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Профиль')]));}
 Widget top(String title)=>Row(children:[IconButton(onPressed:menu,icon:const Icon(Icons.menu)),Expanded(child:Text(title,textAlign:TextAlign.center,style:const TextStyle(fontSize:25,fontWeight:FontWeight.w700))),IconButton(onPressed:()=>setState(()=>tab=4),icon:const Icon(Icons.person_outline))]);
 Widget days(){final base=day.subtract(const Duration(days:3));const names=['ПН','ВТ','СР','ЧТ','ПТ','СБ','ВС'];return SizedBox(height:78,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:7,separatorBuilder:(_,__)=>const SizedBox(width:8),itemBuilder:(_,i){final d=base.add(Duration(days:i)),active=key(d)==key(day);return GestureDetector(onTap:()=>setState(()=>day=d),child:Container(width:58,decoration:BoxDecoration(color:active?blueLight:Colors.white,borderRadius:BorderRadius.circular(16),border:Border.all(color:active?blue:const Color(0xFFE2E6EA))),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(names[d.weekday-1],style:TextStyle(fontSize:12,fontWeight:FontWeight.w700,color:active?blue:muted)),Text('${d.day}',style:TextStyle(fontSize:20,fontWeight:FontWeight.w700,color:active?blue:Colors.black87))]))); }));}
 Widget card(Widget w)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22),boxShadow:const[BoxShadow(color:Color(0x10000000),blurRadius:10,offset:Offset(0,3))]),child:w);
 Widget summary(){final left=(g.calories-kcal).clamp(0,g.calories);return card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Row(children:[Icon(Icons.local_fire_department,color:orange),SizedBox(width:8),Text('Калории',style:TextStyle(fontSize:21,fontWeight:FontWeight.w700))]),const SizedBox(height:10),LinearProgressIndicator(value:(kcal/g.calories).clamp(0.0,1.0).toDouble(),minHeight:8,backgroundColor:blueLight),const SizedBox(height:12),Row(children:[metric('Еда','$kcal'),metric('Упражнение','0'),metric('Осталось','$left',strong:true)]),const SizedBox(height:14),const Row(children:[Icon(Icons.donut_small,color:pink),SizedBox(width:8),Text('Макросы',style:TextStyle(fontSize:21,fontWeight:FontWeight.w700))]),const SizedBox(height:10),Row(children:[macro('Углеводы',carbs,g.carbs),macro('Белки',protein,g.protein),macro('Жиры',fat,g.fat)]),const SizedBox(height:10),Text('🌿  Клетчатка  ${fiber.toStringAsFixed(1)} / 30 г',style:const TextStyle(color:muted))]));}
 Widget metric(String a,String b,{bool strong=false})=>Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(color:muted)),Text(b,style:TextStyle(fontSize:strong?25:21,fontWeight:FontWeight.w700)),const Text('ккал',style:TextStyle(fontSize:11,color:muted))]));
 Widget macro(String a,double v,int t)=>Expanded(child:Padding(padding:const EdgeInsets.only(right:8),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:12,color:muted)),const SizedBox(height:4),LinearProgressIndicator(value:t>0?(v/t).clamp(0.0,1.0).toDouble():0,minHeight:6,backgroundColor:blueLight),Text('${v.round()} / $t г',style:const TextStyle(fontSize:12,fontWeight:FontWeight.w600))])));
 Widget checkin()=>card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Row(children:[Icon(Icons.checklist),SizedBox(width:8),Text('Ежедневный чек-ин',style:TextStyle(fontSize:20,fontWeight:FontWeight.w700))]),const SizedBox(height:10),const Text('• Посмотрите вчерашнюю аналитику и баланс калорий',style:TextStyle(color:blue,fontSize:15)),const SizedBox(height:7),const Text('• Запланируйте завтрак, обед и ужин',style:TextStyle(fontSize:15)),const SizedBox(height:12),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:()=>setState(()=>tab=1),icon:const Icon(Icons.restaurant_menu),label:const Text('План питания'))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:()=>change((){water+=250;}),icon:const Icon(Icons.water_drop_outlined),label:const Text('+250 мл')))])]));
 Widget empty()=>card(Column(children:[const Icon(Icons.restaurant_outlined,size:44,color:muted),const SizedBox(height:7),Text(key(day)==key(DateTime.now())?'Что вы сегодня съели?':'Записей за этот день нет',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w700)),const SizedBox(height:5),const Text('Добавляйте продукты — FitLife посчитает калории, БЖУ и клетчатку.',textAlign:TextAlign.center,style:TextStyle(color:muted)),const SizedBox(height:12),FilledButton.icon(onPressed:addFood,icon:const Icon(Icons.add),label:const Text('Добавить продукт'))]));
 Widget meal(FoodEntry e)=>Padding(padding:const EdgeInsets.only(bottom:10),child:card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(e.food.name,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w700)),Text('${e.grams.round()} г',style:const TextStyle(color:muted)),const SizedBox(height:10),Row(children:[mealM('Ккал','${e.kcal}'),mealM('У','${e.carbs.round()} г'),mealM('Б','${e.protein.round()} г'),mealM('Ж','${e.fat.round()} г')]),Row(mainAxisAlignment:MainAxisAlignment.end,children:[IconButton(onPressed:()=>editFood(e),icon:const Icon(Icons.edit_outlined)),IconButton(onPressed:()=>change(()=>meals.remove(e)),icon:const Icon(Icons.delete_outline))])]));
 Widget mealM(String a,String b)=>Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:11,color:muted)),Text(b,style:const TextStyle(fontWeight:FontWeight.w700))]));
 Widget home()=>ListView(padding:const EdgeInsets.all(16),children:[top('Сегодня'),days(),const SizedBox(height:12),summary(),const SizedBox(height:12),checkin(),const SizedBox(height:14),const Text('Дневник питания',style:TextStyle(fontSize:21,fontWeight:FontWeight.w700)),const SizedBox(height:8),if(today.isEmpty)empty() else ...today.map(meal),const SizedBox(height:80)]);
 Widget nutrition()=>ListView(padding:const EdgeInsets.all(16),children:[top('Питание'),days(),const SizedBox(height:12),summary(),const SizedBox(height:12),Row(children:[const Text('Дневник питания',style:TextStyle(fontSize:21,fontWeight:FontWeight.w700)),const Spacer(),Text('${today.length} записей',style:const TextStyle(color:muted))]),const SizedBox(height:8),if(today.isEmpty)empty() else ...today.map(meal),const SizedBox(height:8),FilledButton.icon(onPressed:addFood,icon:const Icon(Icons.add),label:const Text('Добавить продукт')),const SizedBox(height:80)]);
 Future<void> addFood()async{final f=await showModalBottomSheet<Food>(context:context,showDragHandle:true,isScrollControlled:true,builder:(c)=>SafeArea(child:ListView(shrinkWrap:true,padding:const EdgeInsets.all(16),children:[const Text('Добавить продукт',style:TextStyle(fontSize:23,fontWeight:FontWeight.w700)),...defaultFoods.map((x)=>ListTile(leading:const CircleAvatar(child:Icon(Icons.restaurant)),title:Text(x.name),subtitle:Text('${x.kcal} ккал • Б ${x.protein} • Ж ${x.fat} • У ${x.carbs}'),onTap:()=>Navigator.pop(c,x))])));if(f==null||!mounted)return;final c=TextEditingController(text:'100');final grams=await showDialog<double>(context:context,builder:(x)=>AlertDialog(title:Text(f.name),content:TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Количество, г')),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Отмена')),FilledButton(onPressed:()=>Navigator.pop(x,double.tryParse(c.text.replaceAll(',','.'))),child:const Text('Добавить'))]));c.dispose();if(grams==null||grams<=0||!mounted)return;change(()=>meals.add(FoodEntry.fromFood(f,grams,key(day))));}
 Future<void> editFood(FoodEntry e)async{final c=TextEditingController(text:e.grams.toStringAsFixed(0));final grams=await showDialog<double>(context:context,builder:(x)=>AlertDialog(title:Text(e.food.name),content:TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Количество, г')),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Отмена')),FilledButton(onPressed:()=>Navigator.pop(x,double.tryParse(c.text.replaceAll(',','.'))),child:const Text('Сохранить'))]));c.dispose();if(grams==null||grams<=0||!mounted)return;change((){final i=meals.indexOf(e);if(i>=0)meals[i]=e.copyWith(grams:grams);});}
 Widget weightPage(){final data=List<WeightEntry>.from(weights);if(data.isEmpty){data.add(WeightEntry(start,'Старт',DateTime.now()));if(weight!=start)data.add(WeightEntry(weight,'Сейчас',DateTime.now()));}return ListView(padding:const EdgeInsets.all(16),children:[top('Трекер веса'),Row(children:[Expanded(child:info('Текущий вес','${weight.toStringAsFixed(1)} кг')),const SizedBox(width:10),Expanded(child:info('Целевой вес','${goal.toStringAsFixed(1)} кг'))]),const SizedBox(height:12),card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Text('Прогресс',style:TextStyle(fontSize:19,fontWeight:FontWeight.w700)),const Spacer(),Text('${(progress*100).round()}%',style:const TextStyle(color:blue,fontWeight:FontWeight.w700))]),const SizedBox(height:10),LinearProgressIndicator(value:progress,minHeight:10,backgroundColor:blueLight),const SizedBox(height:10),Text('Осталось сбросить ${((weight-goal).clamp(0.0,999.0)).toStringAsFixed(1)} кг',style:const TextStyle(color:muted))])),const SizedBox(height:12),card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('График веса',style:TextStyle(fontSize:19,fontWeight:FontWeight.w700)),const SizedBox(height:8),SizedBox(height:230,child:WeightChart(entries:data,goal:goal))])),const SizedBox(height:12),Row(children:[const Text('История веса',style:TextStyle(fontSize:21,fontWeight:FontWeight.w700)),const Spacer(),IconButton(onPressed:addWeight,icon:const Icon(Icons.add_circle_outline,color:blue))]),if(weights.isEmpty)card(const Text('Пока нет записей. Добавьте первый вес.',style:TextStyle(color:muted))) else ...weights.reversed.map((e)=>card(Row(children:[const Icon(Icons.scale_outlined,color:blue),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${e.weight.toStringAsFixed(1)} кг',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w700)),Text(e.date,style:const TextStyle(color:muted))])),if(e.weight<start)const Icon(Icons.trending_down,color:green)]))),const SizedBox(height:80)];}
 Widget info(String a,String b)=>card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(Icons.monitor_weight_outlined,color:blue),Text(a,style:const TextStyle(color:muted)),Text(b,style:const TextStyle(fontSize:23,fontWeight:FontWeight.w700))]));
 Future<void> addWeight()async{final c=TextEditingController(text:weight.toStringAsFixed(1));final v=await showDialog<double>(context:context,builder:(x)=>AlertDialog(title:const Text('Записать вес'),content:TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Вес, кг')),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Отмена')),FilledButton(onPressed:()=>Navigator.pop(x,double.tryParse(c.text.replaceAll(',','.'))),child:const Text('Сохранить'))]));c.dispose();if(v==null||v<=0||!mounted)return;final now=DateTime.now();change((){if(weights.isEmpty)start=v;weight=v;weights.add(WeightEntry(v,'${now.day.toString().padLeft(2,'0')}.${now.month.toString().padLeft(2,'0')}.${now.year}',now));});}
 Widget stats()=>ListView(padding:const EdgeInsets.all(16),children:[top('Статистика'),card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Результат',style:TextStyle(fontSize:20,fontWeight:FontWeight.w700)),const SizedBox(height:12),Row(children:[stat('Сброшено','${(start-weight).toStringAsFixed(1)} кг'),stat('До цели','${((weight-goal).clamp(0.0,999.0)).toStringAsFixed(1)} кг')]),const SizedBox(height:8),Row(children:[stat('Сегодня','$kcal ккал'),stat('Вода','$water мл')])])),const SizedBox(height:12),card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Питание сегодня',style:TextStyle(fontSize:20,fontWeight:FontWeight.w700)),const SizedBox(height:10),line('Калории',kcal.toDouble(),g.calories),line('Белки',protein,g.protein),line('Жиры',fat,g.fat),line('Углеводы',carbs,g.carbs),line('Клетчатка',fiber,30)])),const SizedBox(height:80)];
 Widget stat(String a,String b)=>Expanded(child:Container(margin:const EdgeInsets.only(right:8),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:blueLight,borderRadius:BorderRadius.circular(14)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(color:muted)),Text(b,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w700))])));
 Widget line(String a,double v,num t)=>Padding(padding:const EdgeInsets.only(bottom:11),child:Column(children:[Row(children:[Text(a),const Spacer(),Text('${v.round()} / ${t.round()}')]),LinearProgressIndicator(value:t>0?(v/t).clamp(0.0,1.0).toDouble():0,minHeight:7,backgroundColor:blueLight)]));
 Widget profile()=>ListView(padding:const EdgeInsets.all(16),children:[top('Профиль'),card(Column(children:[const CircleAvatar(radius:38,backgroundColor:blueLight,child:Icon(Icons.person,size:44,color:blue)),const SizedBox(height:8),const Text('Мой профиль',style:TextStyle(fontSize:22,fontWeight:FontWeight.w700)),row('Пол',sex),row('Возраст','$age лет'),row('Рост','$height см'),row('Вес','${weight.toStringAsFixed(1)} кг'),row('Цель','${goal.toStringAsFixed(1)} кг'),row('Цель калорий','${g.calories} ккал'),FilledButton.icon(onPressed:editProfile,icon:const Icon(Icons.edit),label:const Text('Изменить профиль'))])),const SizedBox(height:12),card(Column(children:[ListTile(leading:const Icon(Icons.flag_outlined,color:blue),title:const Text('Ежедневные цели'),subtitle:Text('${g.calories} ккал • Б ${g.protein} г • Ж ${g.fat} г • У ${g.carbs} г'),onTap:showGoals),ListTile(leading:const Icon(Icons.groups_outlined,color:blue),title:const Text('Группы'),subtitle:const Text('Совместное отслеживание'),onTap:showGroups)])),const SizedBox(height:80)];
 Widget row(String a,String b)=>ListTile(title:Text(a),trailing:Text(b,style:const TextStyle(fontWeight:FontWeight.w600)));
 Future<void> editProfile()async{final a=TextEditingController(text:'$age'),h=TextEditingController(text:'$height'),w=TextEditingController(text:weight.toStringAsFixed(1)),go=TextEditingController(text:goal.toStringAsFixed(1));final r=await showDialog<List<double>>(context:context,builder:(x)=>AlertDialog(title:const Text('Профиль'),content:SingleChildScrollView(child:Column(children:[TextField(controller:a,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Возраст')),TextField(controller:h,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Рост, см')),TextField(controller:w,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Вес, кг')),TextField(controller:go,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Цель, кг'))])),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Отмена')),FilledButton(onPressed:()=>Navigator.pop(x,[double.tryParse(a.text)??0,double.tryParse(h.text)??0,double.tryParse(w.text.replaceAll(',','.'))??0,double.tryParse(go.text.replaceAll(',','.'))??0]),child:const Text('Сохранить'))]));a.dispose();h.dispose();w.dispose();go.dispose();if(r==null||r.any((v)=>v<=0)||!mounted)return;change((){age=r[0].round();height=r[1].round();weight=r[2];goal=r[3];});}
 void showGoals()=>showDialog(context:context,builder:(x)=>AlertDialog(title:const Text('Ежедневные цели'),content:Column(mainAxisSize:MainAxisSize.min,children:[row('Калории','${g.calories} ккал'),row('Белки','${g.protein} г'),row('Жиры','${g.fat} г'),row('Углеводы','${g.carbs} г'),row('Клетчатка','30 г')]),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Закрыть'))]));
 void showGroups()=>showModalBottomSheet(context:context,showDragHandle:true,builder:(x)=>SafeArea(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.groups,size:60,color:blue),const SizedBox(height:8),const Text('Вместе лучше',style:TextStyle(fontSize:26,fontWeight:FontWeight.w700)),const SizedBox(height:8),const Text('Отслеживайте питание вместе с друзьями, семьёй или специалистом.',textAlign:TextAlign.center,style:TextStyle(color:muted)),const SizedBox(height:16),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:(){},icon:const Icon(Icons.add),label:const Text('Создать группу'))),SizedBox(width:double.infinity,child:OutlinedButton.icon(onPressed:(){},icon:const Icon(Icons.person_add_alt_1),label:const Text('Присоединиться к группе')))]))));
 void menu()=>showModalBottomSheet(context:context,showDragHandle:true,builder:(x)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[ListTile(leading:const Icon(Icons.home),title:const Text('Сегодня'),onTap:(){Navigator.pop(x);setState(()=>tab=0);}),ListTile(leading:const Icon(Icons.restaurant),title:const Text('Питание'),onTap:(){Navigator.pop(x);setState(()=>tab=1);}),ListTile(leading:const Icon(Icons.monitor_weight),title:const Text('Вес'),onTap:(){Navigator.pop(x);setState(()=>tab=2);}),ListTile(leading:const Icon(Icons.insights),title:const Text('Статистика'),onTap:(){Navigator.pop(x);setState(()=>tab=3);}),ListTile(leading:const Icon(Icons.person),title:const Text('Профиль'),onTap:(){Navigator.pop(x);setState(()=>tab=4);})])));
}

class FoodEntry{final Food food;final double grams;final String dateKey;const FoodEntry(this.food,this.grams,this.dateKey);factory FoodEntry.fromFood(Food f,double g,String d)=>FoodEntry(f,g,d);int get kcal=>(food.kcal*grams/100).round();double get protein=>food.protein*grams/100;double get fat=>food.fat*grams/100;double get carbs=>food.carbs*grams/100;double get fiber=>food.fiber*grams/100;FoodEntry copyWith({double? grams})=>FoodEntry(food,grams??this.grams,dateKey);Map<String,dynamic> toJson()=>{'food':food.toJson(),'grams':grams,'dateKey':dateKey};static FoodEntry? fromJson(Map<String,dynamic> j){final f=j['food'],gr=(j['grams'] as num?)?.toDouble(),d=j['dateKey'] as String?;if(f is! Map||gr==null||d==null||gr<=0)return null;return FoodEntry(Food.fromJson(Map<String,dynamic>.from(f)),gr,d);}}
class WeightEntry{final double weight;final String date;final DateTime dateTime;const WeightEntry(this.weight,this.date,this.dateTime);Map<String,dynamic> toJson()=>{'weight':weight,'date':date,'dateTime':dateTime.toIso8601String()};static WeightEntry? fromJson(Map<String,dynamic> j){final w=(j['weight'] as num?)?.toDouble(),d=j['date'] as String?;if(w==null||d==null)return null;return WeightEntry(w,d,DateTime.tryParse(j['dateTime'] as String? ?? '')??DateTime.now());}}
class WeightChart extends StatelessWidget{final List<WeightEntry> entries;final double goal;const WeightChart({super.key,required this.entries,required this.goal});@override Widget build(BuildContext c)=>CustomPaint(painter:ChartPainter(entries,goal),child:const SizedBox.expand());}
class ChartPainter extends CustomPainter{final List<WeightEntry> e;final double goal;const ChartPainter(this.e,this.goal);@override void paint(Canvas c,Size s){if(e.isEmpty)return;final v=e.map((x)=>x.weight).toList(),min=([...v,goal].reduce((a,b)=>a<b?a:b)-2),max=([...v,goal].reduce((a,b)=>a>b?a:b)+2),range=(max-min).clamp(1.0,1000.0),l=38.0,t=10.0,r=s.width-6,b=s.height-15;final grid=Paint()..color=const Color(0xFFE1E6EA);for(int i=0;i<=4;i++){final y=t+(b-t)*i/4;c.drawLine(Offset(l,y),Offset(r,y),grid);}final gy=b-((goal-min)/range)*(b-t);final gp=Paint()..color=green..strokeWidth=2;c.drawLine(Offset(l,gy),Offset(r,gy),gp);final p=Path(),line=Paint()..color=blue..strokeWidth=3..style=PaintingStyle.stroke,dot=Paint()..color=blue;for(int i=0;i<v.length;i++){final x=l+(r-l)*(v.length==1?.5:i/(v.length-1)),y=b-((v[i]-min)/range)*(b-t);if(i==0)p.moveTo(x,y);else p.lineTo(x,y);c.drawCircle(Offset(x,y),4,dot);}c.drawPath(p,line);}@override bool shouldRepaint(covariant ChartPainter old)=>true;}
const defaultFoods=<Food>[Food(name:'Куриная грудка',kcal:110,protein:23,fat:1.9,carbs:0),Food(name:'Яйцо',kcal:157,protein:12.7,fat:10.9,carbs:.7),Food(name:'Овсянка сухая',kcal:366,protein:12.3,fat:6.1,carbs:59.5,fiber:8),Food(name:'Гречка сухая',kcal:343,protein:13.6,fat:3.3,carbs:71.5,fiber:10),Food(name:'Картофель',kcal:77,protein:2,fat:.1,carbs:17.5,fiber:2.2),Food(name:'Рис сухой',kcal:344,protein:6.7,fat:.7,carbs:78.9,fiber:2),Food(name:'Помидор',kcal:20,protein:1.1,fat:.2,carbs:3.7,fiber:1.2),Food(name:'Перец красный',kcal:27,protein:1,fat:.3,carbs:5.3,fiber:2.1),Food(name:'Яблоко',kcal:52,protein:.3,fat:.2,carbs:13.8,fiber:2.4),Food(name:'Греческий йогурт',kcal:73,protein:9.9,fat:2,carbs:3.9),Food(name:'Ветчина из индейки',kcal:84,protein:18,fat:2,carbs:2),Food(name:'Черника',kcal:57,protein:.7,fat:.3,carbs:14.5,fiber:2.4)];
