import 'package:flutter/material.dart';
import '../core/models/food.dart';
import '../core/nutrition/nutrition_calculator.dart';
import '../data/repositories/fitlife_storage.dart';

const _bg = Color(0xFFF7F9FB);
const _blue = Color(0xFF3F6F9F);
const _blueLight = Color(0xFFE8F0F7);
const _green = Color(0xFF5BAF78);
const _orange = Color(0xFFF3A33B);
const _pink = Color(0xFFD85A9B);
const _text = Color(0xFF20252A);
const _muted = Color(0xFF7B858E);

class FitLifeApp extends StatelessWidget {
  const FitLifeApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false,
    title: 'FitLife',
    theme: ThemeData(useMaterial3: true, scaffoldBackgroundColor: _bg,
      colorScheme: ColorScheme.fromSeed(seedColor: _blue),
      textTheme: const TextTheme(bodyLarge: TextStyle(color: _text), bodyMedium: TextStyle(color: _text), titleLarge: TextStyle(color: _text, fontWeight: FontWeight.w700), headlineSmall: TextStyle(color: _text, fontWeight: FontWeight.w700))),
    home: const FitLifeShell(),
  );
}

class FitLifeShell extends StatefulWidget {
  const FitLifeShell({super.key});
  @override State<FitLifeShell> createState() => _FitLifeShellState();
}

class _FitLifeShellState extends State<FitLifeShell> {
  final storage = const FitLifeStorage();
  int tab = 0;
  DateTime selectedDay = DateTime.now();
  double weight = 104.2, startWeight = 110, goalWeight = 85;
  int age = 36, height = 175, water = 0;
  String sex = 'Мужской';
  double activity = 1.2;
  final meals = <FoodEntry>[];
  final weights = <WeightEntry>[];
  bool loaded = false;

  NutritionGoals get goals => const NutritionCalculator().calculate(weight: weight, height: height, age: age, sex: sex, activity: activity);
  static String key(DateTime d) => '${d.year}-${d.month.toString().padLeft(2,'0')}-${d.day.toString().padLeft(2,'0')}';
  bool get isToday => key(selectedDay) == key(DateTime.now());
  List<FoodEntry> get dayMeals => meals.where((e) => e.dateKey == key(selectedDay)).toList();
  int get kcal => dayMeals.fold(0, (s,e) => s + e.kcal);
  double get protein => dayMeals.fold(0.0, (s,e) => s + e.protein);
  double get fat => dayMeals.fold(0.0, (s,e) => s + e.fat);
  double get carbs => dayMeals.fold(0.0, (s,e) => s + e.carbs);
  double get fiber => dayMeals.fold(0.0, (s,e) => s + e.fiber);
  double get progress { final total = startWeight-goalWeight; return total <= 0 ? 0 : ((startWeight-weight)/total).clamp(0.0,1.0).toDouble(); }

  @override void initState() { super.initState(); _load(); }
  Future<void> _load() async {
    final sw=await storage.readDouble('weight'), ss=await storage.readDouble('startWeight'), sg=await storage.readDouble('goalWeight');
    final a=await storage.readInt('age'), h=await storage.readInt('height'), w=await storage.readInt('water'), sx=await storage.readString('sex');
    final mr=await storage.readList('meals'), wr=await storage.readList('weights');
    if (!mounted) return;
    setState(() { if(sw!=null)weight=sw; if(ss!=null)startWeight=ss; if(sg!=null)goalWeight=sg; if(a!=null)age=a; if(h!=null)height=h; if(w!=null)water=w; if(sx!=null)sex=sx; meals..clear()..addAll(mr.map(FoodEntry.fromJson).whereType<FoodEntry>()); weights..clear()..addAll(wr.map(WeightEntry.fromJson).whereType<WeightEntry>()); loaded=true; });
  }
  Future<void> _save() async { await storage.writeDouble('weight',weight); await storage.writeDouble('startWeight',startWeight); await storage.writeDouble('goalWeight',goalWeight); await storage.writeInt('age',age); await storage.writeInt('height',height); await storage.writeInt('water',water); await storage.writeString('sex',sex); await storage.writeList('meals',meals.map((e)=>e.toJson()).toList()); await storage.writeList('weights',weights.map((e)=>e.toJson()).toList()); }
  void changed(VoidCallback f){ setState(f); _save(); }

  @override Widget build(BuildContext context){
    if(!loaded)return const Scaffold(body:Center(child:CircularProgressIndicator()));
    final pages=[_home(),_nutrition(),_weight(),_statistics(),_profile()];
    return Scaffold(body:SafeArea(child:pages[tab]),bottomNavigationBar:NavigationBar(backgroundColor:Colors.white,indicatorColor:_blueLight,selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const [
      NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Сегодня'), NavigationDestination(icon:Icon(Icons.restaurant_outlined),selectedIcon:Icon(Icons.restaurant),label:'Питание'), NavigationDestination(icon:Icon(Icons.monitor_weight_outlined),selectedIcon:Icon(Icons.monitor_weight),label:'Вес'), NavigationDestination(icon:Icon(Icons.insights_outlined),selectedIcon:Icon(Icons.insights),label:'Статистика'), NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Профиль') ]));
  }

  Widget top(String title)=>Row(children:[IconButton(icon:const Icon(Icons.menu),onPressed:menu),Expanded(child:Text(title,textAlign:TextAlign.center,style:const TextStyle(fontSize:25,fontWeight:FontWeight.w700))),IconButton(onPressed:()=>setState(()=>tab=4),icon:const Icon(Icons.person_outline))]);
  Widget dates(){ final base=selectedDay.subtract(const Duration(days:3)); const names=['ПН','ВТ','СР','ЧТ','ПТ','СБ','ВС']; return SizedBox(height:78,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:7,separatorBuilder:(_,__)=>const SizedBox(width:8),itemBuilder:(c,i){final d=base.add(Duration(days:i));final active=key(d)==key(selectedDay);return GestureDetector(onTap:()=>setState(()=>selectedDay=d),child:Container(width:58,padding:const EdgeInsets.symmetric(vertical:8),decoration:BoxDecoration(color:active?_blueLight:Colors.white,borderRadius:BorderRadius.circular(16),border:Border.all(color:active?_blue:const Color(0xFFE2E6EA),width:active?1.5:1)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(names[d.weekday-1],style:TextStyle(fontSize:12,fontWeight:FontWeight.w700,color:active?_blue:_muted)),const SizedBox(height:3),Text('${d.day}',style:TextStyle(fontSize:20,fontWeight:FontWeight.w700,color:active?_blue:_text))]))); })); }

  Widget card(Widget child)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22),boxShadow:const[BoxShadow(color:Color(0x10000000),blurRadius:12,offset:Offset(0,3))]),child:child);
  Widget summary(){ final left=(goals.calories-kcal).clamp(0,goals.calories); return card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.local_fire_department,color:_orange),const SizedBox(width:8),const Text('Калории',style:TextStyle(fontSize:21,fontWeight:FontWeight.w700))]),const SizedBox(height:12),ClipRRect(borderRadius:BorderRadius.circular(20),child:LinearProgressIndicator(value:(kcal/goals.calories).clamp(0.0,1.0).toDouble(),minHeight:8,backgroundColor:_blueLight)),const SizedBox(height:12),Row(children:[metric('Еда','$kcal'),metric('Упражнение','0'),metric('Осталось','$left',strong:true)]),const SizedBox(height:16),Row(children:[const Icon(Icons.donut_small,color:_pink),const SizedBox(width:8),const Text('Макросы',style:TextStyle(fontSize:21,fontWeight:FontWeight.w700))]),const SizedBox(height:12),Row(children:[macro('Углеводы',carbs,goals.carbs),macro('Белки',protein,goals.protein),macro('Жиры',fat,goals.fat)]),const SizedBox(height:12),Text('🌿  Клетчатка  ${fiber.toStringAsFixed(1)} / 30 г',style:const TextStyle(color:_muted))])); }
  Widget metric(String t,String v,{bool strong=false})=>Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(color:_muted)),Text(v,style:TextStyle(fontSize:strong?25:22,fontWeight:FontWeight.w700)),const Text('ккал',style:TextStyle(fontSize:12,color:_muted))]));
  Widget macro(String t,double v,int target)=>Expanded(child:Padding(padding:const EdgeInsets.only(right:10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(color:_muted,fontSize:13)),const SizedBox(height:5),ClipRRect(borderRadius:BorderRadius.circular(10),child:LinearProgressIndicator(value:target>0?(v/target).clamp(0.0,1.0).toDouble():0,minHeight:6,backgroundColor:_blueLight)),const SizedBox(height:5),Text('${v.round()} / $target г',style:const TextStyle(fontSize:13,fontWeight:FontWeight.w600))])));

  Widget checkin()=>card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.checklist),const SizedBox(width:9),const Text('Ежедневный чек-ин',style:TextStyle(fontSize:20,fontWeight:FontWeight.w700))]),const SizedBox(height:12),const Text('•  Посмотрите вчерашнюю аналитику и баланс калорий',style:TextStyle(fontSize:16,height:1.35,color:_blue)),const SizedBox(height:8),const Text('•  Запланируйте, что вы будете есть на завтрак, обед и ужин',style:TextStyle(fontSize:16,height:1.35)),const SizedBox(height:14),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:()=>setState(()=>tab=1),icon:const Icon(Icons.restaurant_menu),label:const Text('План питания'))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:()=>changed(()=>water+=250),icon:const Icon(Icons.water_drop_outlined),label:const Text('+250 мл')))])]));
  Widget empty()=>card(Column(children:[const Icon(Icons.restaurant_outlined,size:46,color:_muted),const SizedBox(height:8),Text(isToday?'Что вы сегодня съели?':'Записей за этот день нет',style:const TextStyle(fontSize:19,fontWeight:FontWeight.w700)),const SizedBox(height:5),const Text('Добавляйте продукты — FitLife посчитает калории, БЖУ и клетчатку.',textAlign:TextAlign.center,style:TextStyle(color:_muted)),const SizedBox(height:14),FilledButton.icon(onPressed:addFood,icon:const Icon(Icons.add),label:const Text('Добавить продукт'))]));
  Widget meal(FoodEntry e)=>Padding(padding:const EdgeInsets.only(bottom:10),child:card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(e.food.name,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w700)),Text('${e.grams.round()} г',style:const TextStyle(color:_muted)),const SizedBox(height:12),Row(children:[mealMetric('Ккал','${e.kcal}'),mealMetric('У','${e.carbs.round()} г'),mealMetric('Б','${e.protein.round()} г'),mealMetric('Ж','${e.fat.round()} г')]),Row(mainAxisAlignment:MainAxisAlignment.end,children:[IconButton(onPressed:()=>editFood(e),icon:const Icon(Icons.edit_outlined)),IconButton(onPressed:()=>changed(()=>meals.remove(e)),icon:const Icon(Icons.delete_outline))])]));
  Widget mealMetric(String a,String b)=>Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:11,color:_muted)),Text(b,style:const TextStyle(fontWeight:FontWeight.w700))]));

  Widget home()=>ListView(padding:const EdgeInsets.fromLTRB(16,8,16,24),children:[top('Сегодня'),dates(),const SizedBox(height:12),summary(),const SizedBox(height:12),checkin(),const SizedBox(height:12),const Text('Дневник питания',style:TextStyle(fontSize:21,fontWeight:FontWeight.w700)),const SizedBox(height:10),if(dayMeals.isEmpty)empty() else ...dayMeals.map(meal),const SizedBox(height:100)]);
  Widget nutrition()=>ListView(padding:const EdgeInsets.fromLTRB(16,8,16,24),children:[top('Питание'),dates(),const SizedBox(height:12),summary(),const SizedBox(height:12),Row(children:[const Text('Дневник питания',style:TextStyle(fontSize:21,fontWeight:FontWeight.w700)),const Spacer(),Text('${dayMeals.length} записей',style:const TextStyle(color:_muted))]),const SizedBox(height:10),if(dayMeals.isEmpty)empty() else ...dayMeals.map(meal),const SizedBox(height:12),FilledButton.icon(onPressed:addFood,icon:const Icon(Icons.add),label:const Text('Добавить продукт')),const SizedBox(height:100)]);

  Future<void> addFood() async { final f=await showModalBottomSheet<Food>(context:context,showDragHandle:true,isScrollControlled:true,builder:(c)=>SafeArea(child:ListView(shrinkWrap:true,padding:const EdgeInsets.all(16),children:[const Text('Добавить продукт',style:TextStyle(fontSize:24,fontWeight:FontWeight.w700)),const SizedBox(height:8),...defaultFoods.map((x)=>ListTile(leading:const CircleAvatar(child:Icon(Icons.restaurant)),title:Text(x.name),subtitle:Text('${x.kcal} ккал • Б ${x.protein} • Ж ${x.fat} • У ${x.carbs}'),onTap:()=>Navigator.pop(c,x)))]))); if(f==null||!mounted)return; final c=TextEditingController(text:'100'); final g=await showDialog<double>(context:context,builder:(x)=>AlertDialog(title:Text(f.name),content:TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Количество, г')),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Отмена')),FilledButton(onPressed:()=>Navigator.pop(x,double.tryParse(c.text.replaceAll(',','.'))),child:const Text('Добавить'))]));c.dispose();if(g==null||g<=0||!mounted)return;changed(()=>meals.add(FoodEntry.fromFood(f,g,key(selectedDay)))); }
  Future<void> editFood(FoodEntry e) async { final c=TextEditingController(text:e.grams.toStringAsFixed(0)); final g=await showDialog<double>(context:context,builder:(x)=>AlertDialog(title:Text(e.food.name),content:TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Количество, г')),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Отмена')),FilledButton(onPressed:()=>Navigator.pop(x,double.tryParse(c.text.replaceAll(',','.'))),child:const Text('Сохранить'))]));c.dispose();if(g==null||g<=0||!mounted)return;changed(()=>meals[meals.indexOf(e)]=e.copyWith(grams:g)); }

  Widget weightPage(){ final data=List<WeightEntry>.from(weights);if(data.isEmpty)data.add(WeightEntry(startWeight,'Старт',DateTime.now()));if(weight!=startWeight&&data.length==1)data.add(WeightEntry(weight,'Сейчас',DateTime.now()));return ListView(padding:const EdgeInsets.fromLTRB(16,8,16,24),children:[top('Трекер веса'),Row(children:[Expanded(child:info('Текущий вес','${weight.toStringAsFixed(1)} кг')),const SizedBox(width:10),Expanded(child:info('Целевой вес','${goalWeight.toStringAsFixed(1)} кг'))]),const SizedBox(height:12),card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Text('Прогресс',style:TextStyle(fontSize:19,fontWeight:FontWeight.w700)),const Spacer(),Text('${(progress*100).round()}%',style:const TextStyle(color:_blue,fontWeight:FontWeight.w700))]),const SizedBox(height:12),LinearProgressIndicator(value:progress,minHeight:10,backgroundColor:_blueLight),const SizedBox(height:12),Text('Осталось сбросить ${((weight-goalWeight).clamp(0.0,999.0)).toStringAsFixed(1)} кг',style:const TextStyle(color:_muted))])),const SizedBox(height:12),card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('График веса',style:TextStyle(fontSize:19,fontWeight:FontWeight.w700)),const SizedBox(height:12),SizedBox(height:230,child:WeightChart(entries:data,goal:goalWeight))])),const SizedBox(height:12),Row(children:[const Text('История веса',style:TextStyle(fontSize:21,fontWeight:FontWeight.w700)),const Spacer(),IconButton(onPressed:addWeight,icon:const Icon(Icons.add_circle_outline,color:_blue))]),if(weights.isEmpty)card(const Text('Пока нет записей. Добавьте первый вес.',style:TextStyle(color:_muted))) else ...weights.reversed.map((e)=>card(Row(children:[const Icon(Icons.scale_outlined,color:_blue),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${e.weight.toStringAsFixed(1)} кг',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w700)),Text(e.date,style:const TextStyle(color:_muted))])),if(e.weight<startWeight)const Icon(Icons.trending_down,color:_green)]))),const SizedBox(height:100)]; }
  Widget info(String a,String b)=>card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(Icons.monitor_weight_outlined,color:_blue),const SizedBox(height:8),Text(a,style:const TextStyle(color:_muted)),Text(b,style:const TextStyle(fontSize:24,fontWeight:FontWeight.w700))]));
  Widget _weight()=>weightPage();
  Future<void> addWeight() async { final c=TextEditingController(text:weight.toStringAsFixed(1));final v=await showDialog<double>(context:context,builder:(x)=>AlertDialog(title:const Text('Записать вес'),content:TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Вес, кг')),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Отмена')),FilledButton(onPressed:()=>Navigator.pop(x,double.tryParse(c.text.replaceAll(',','.'))),child:const Text('Сохранить'))]));c.dispose();if(v==null||v<=0||!mounted)return;final now=DateTime.now();changed(()=>{if(weights.isEmpty)startWeight=v;weight=v;weights.add(WeightEntry(v,'${now.day.toString().padLeft(2,'0')}.${now.month.toString().padLeft(2,'0')}.${now.year}',now))}); }

  Widget _statistics()=>ListView(padding:const EdgeInsets.fromLTRB(16,8,16,24),children:[top('Статистика'),card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Результат',style:TextStyle(fontSize:20,fontWeight:FontWeight.w700)),const SizedBox(height:16),Row(children:[stat('Сброшено','${(startWeight-weight).toStringAsFixed(1)} кг'),stat('До цели','${((weight-goalWeight).clamp(0.0,999.0)).toStringAsFixed(1)} кг')]),const SizedBox(height:10),Row(children:[stat('Сегодня','$kcal ккал'),stat('Вода','$water мл')])])),const SizedBox(height:12),card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Питание сегодня',style:TextStyle(fontSize:20,fontWeight:FontWeight.w700)),const SizedBox(height:12),line('Калории',kcal.toDouble(),goals.calories),line('Белки',protein,goals.protein),line('Жиры',fat,goals.fat),line('Углеводы',carbs,goals.carbs),line('Клетчатка',fiber,30)])),const SizedBox(height:100)]);
  Widget stat(String a,String b)=>Expanded(child:Container(margin:const EdgeInsets.only(right:8),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:_blueLight,borderRadius:BorderRadius.circular(14)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(color:_muted)),Text(b,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w700))])));
  Widget line(String a,double v,num t)=>Padding(padding:const EdgeInsets.only(bottom:12),child:Column(children:[Row(children:[Text(a),const Spacer(),Text('${v.round()} / ${t.round()}')]),LinearProgressIndicator(value:t>0?(v/t).clamp(0.0,1.0).toDouble():0,backgroundColor:_blueLight,minHeight:7)]));

  Widget _profile()=>ListView(padding:const EdgeInsets.fromLTRB(16,8,16,24),children:[top('Профиль'),card(Column(children:[const CircleAvatar(radius:38,backgroundColor:_blueLight,child:Icon(Icons.person,size:44,color:_blue)),const SizedBox(height:10),const Text('Мой профиль',style:TextStyle(fontSize:22,fontWeight:FontWeight.w700)),const SizedBox(height:10),row('Пол',sex),row('Возраст','$age лет'),row('Рост','$height см'),row('Вес','${weight.toStringAsFixed(1)} кг'),row('Цель','${goalWeight.toStringAsFixed(1)} кг'),row('Цель калорий','${goals.calories} ккал'),const SizedBox(height:8),FilledButton.icon(onPressed:editProfile,icon:const Icon(Icons.edit),label:const Text('Изменить профиль'))])),const SizedBox(height:12),card(Column(children:[ListTile(leading:const Icon(Icons.flag_outlined,color:_blue),title:const Text('Ежедневные цели'),subtitle:Text('${goals.calories} ккал • Б ${goals.protein} г • Ж ${goals.fat} г • У ${goals.carbs} г'),onTap:showGoals),ListTile(leading:const Icon(Icons.groups_outlined,color:_blue),title:const Text('Группы'),subtitle:const Text('Совместное отслеживание'),onTap:showGroups)])),const SizedBox(height:100)];
  Widget row(String a,String b)=>ListTile(title:Text(a),trailing:Text(b,style:const TextStyle(fontWeight:FontWeight.w600)));
  Future<void> editProfile() async {final a=TextEditingController(text:'$age'),h=TextEditingController(text:'$height'),w=TextEditingController(text:weight.toStringAsFixed(1)),g=TextEditingController(text:goalWeight.toStringAsFixed(1));final r=await showDialog<List<double>>(context:context,builder:(x)=>AlertDialog(title:const Text('Профиль'),content:SingleChildScrollView(child:Column(children:[TextField(controller:a,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Возраст')),TextField(controller:h,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Рост, см')),TextField(controller:w,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Вес, кг')),TextField(controller:g,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Цель, кг'))])),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Отмена')),FilledButton(onPressed:()=>Navigator.pop(x,[double.tryParse(a.text)??0,double.tryParse(h.text)??0,double.tryParse(w.text.replaceAll(',','.'))??0,double.tryParse(g.text.replaceAll(',','.'))??0]),child:const Text('Сохранить'))]));a.dispose();h.dispose();w.dispose();g.dispose();if(r==null||r.any((v)=>v<=0)||!mounted)return;changed(()=>{age=r[0].round();height=r[1].round();weight=r[2];goalWeight=r[3]});}
  void showGoals()=>showDialog(context:context,builder:(x)=>AlertDialog(title:const Text('Ежедневные цели'),content:Column(mainAxisSize:MainAxisSize.min,children:[row('Калории','${goals.calories} ккал'),row('Белки','${goals.protein} г'),row('Жиры','${goals.fat} г'),row('Углеводы','${goals.carbs} г'),row('Клетчатка','30 г')]),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Закрыть'))]));
  void showGroups()=>showModalBottomSheet(context:context,showDragHandle:true,builder:(x)=>SafeArea(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.groups,size:60,color:_blue),const SizedBox(height:10),const Text('Вместе лучше',style:TextStyle(fontSize:26,fontWeight:FontWeight.w700)),const SizedBox(height:8),const Text('Отслеживайте питание вместе с друзьями, семьёй или специалистом.',textAlign:TextAlign.center,style:TextStyle(color:_muted)),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:(){},icon:const Icon(Icons.add),label:const Text('Создать группу'))),const SizedBox(height:8),SizedBox(width:double.infinity,child:OutlinedButton.icon(onPressed:(){},icon:const Icon(Icons.person_add_alt_1),label:const Text('Присоединиться к группе')))]))));
  void menu()=>showModalBottomSheet(context:context,showDragHandle:true,builder:(x)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[ListTile(leading:const Icon(Icons.home_outlined),title:const Text('Сегодня'),onTap:(){Navigator.pop(x);setState(()=>tab=0);}),ListTile(leading:const Icon(Icons.restaurant_outlined),title:const Text('Питание'),onTap:(){Navigator.pop(x);setState(()=>tab=1);}),ListTile(leading:const Icon(Icons.monitor_weight_outlined),title:const Text('Вес'),onTap:(){Navigator.pop(x);setState(()=>tab=2);}),ListTile(leading:const Icon(Icons.insights_outlined),title:const Text('Статистика'),onTap:(){Navigator.pop(x);setState(()=>tab=3);}),ListTile(leading:const Icon(Icons.person_outline),title:const Text('Профиль'),onTap:(){Navigator.pop(x);setState(()=>tab=4);})])));
}

class FoodEntry { final Food food; final double grams; final String dateKey; const FoodEntry(this.food,this.grams,this.dateKey); factory FoodEntry.fromFood(Food f,double g,String d)=>FoodEntry(f,g,d); int get kcal=>(food.kcal*grams/100).round(); double get protein=>food.protein*grams/100; double get fat=>food.fat*grams/100; double get carbs=>food.carbs*grams/100; double get fiber=>food.fiber*grams/100; FoodEntry copyWith({double? grams})=>FoodEntry(food,grams??this.grams,dateKey); Map<String,dynamic> toJson()=>{'food':food.toJson(),'grams':grams,'dateKey':dateKey}; static FoodEntry? fromJson(Map<String,dynamic> j){final f=j['food'];final g=(j['grams'] as num?)?.toDouble();final d=j['dateKey'] as String?;if(f is! Map||g==null||d==null||g<=0)return null;return FoodEntry(Food.fromJson(Map<String,dynamic>.from(f)),g,d);}}
class WeightEntry { final double weight; final String date; final DateTime dateTime; const WeightEntry(this.weight,this.date,this.dateTime); Map<String,dynamic> toJson()=>{'weight':weight,'date':date,'dateTime':dateTime.toIso8601String()}; static WeightEntry? fromJson(Map<String,dynamic> j){final w=(j['weight'] as num?)?.toDouble();final d=j['date'] as String?;if(w==null||d==null)return null;return WeightEntry(w,d,DateTime.tryParse(j['dateTime'] as String? ?? '')??DateTime.now());}}
class WeightChart extends StatelessWidget { final List<WeightEntry> entries; final double goal; const WeightChart({super.key,required this.entries,required this.goal}); @override Widget build(BuildContext c)=>CustomPaint(painter:_ChartPainter(entries,goal),child:const SizedBox.expand()); }
class _ChartPainter extends CustomPainter { final List<WeightEntry> e; final double goal; const _ChartPainter(this.e,this.goal); @override void paint(Canvas c,Size s){if(e.isEmpty)return;final vals=e.map((x)=>x.weight).toList();final min=( [...vals,goal].reduce((a,b)=>a<b?a:b)-2);final max=( [...vals,goal].reduce((a,b)=>a>b?a:b)+2);final range=(max-min).clamp(1.0,1000.0);final l=42.0,t=12.0,r=s.width-8,b=s.height-25;final grid=Paint()..color=const Color(0xFFE1E6EA);for(int i=0;i<=4;i++){final y=t+(b-t)*i/4;c.drawLine(Offset(l,y),Offset(r,y),grid);}final gy=b-((goal-min)/range)*(b-t);final gp=Paint()..color=_green..strokeWidth=2;c.drawLine(Offset(l,gy),Offset(r,gy),gp);final line=Paint()..color=_blue..strokeWidth=3..style=PaintingStyle.stroke;final dot=Paint()..color=_blue;final p=Path();for(int i=0;i<vals.length;i++){final x=l+(r-l)*(vals.length==1?.5:i/(vals.length-1));final y=b-((vals[i]-min)/range)*(b-t);if(i==0)p.moveTo(x,y);else p.lineTo(x,y);c.drawCircle(Offset(x,y),4,dot);}c.drawPath(p,line);} @override bool shouldRepaint(covariant _ChartPainter old)=>true; }

const defaultFoods=<Food>[
 Food(name:'Куриная грудка',kcal:110,protein:23,fat:1.9,carbs:0,fiber:0), Food(name:'Яйцо',kcal:157,protein:12.7,fat:10.9,carbs:.7), Food(name:'Овсянка сухая',kcal:366,protein:12.3,fat:6.1,carbs:59.5,fiber:8), Food(name:'Гречка сухая',kcal:343,protein:13.6,fat:3.3,carbs:71.5,fiber:10), Food(name:'Картофель',kcal:77,protein:2,fat:.1,carbs:17.5,fiber:2.2), Food(name:'Рис сухой',kcal:344,protein:6.7,fat:.7,carbs:78.9,fiber:2), Food(name:'Помидор',kcal:20,protein:1.1,fat:.2,carbs:3.7,fiber:1.2), Food(name:'Перец красный',kcal:27,protein:1,fat:.3,carbs:5.3,fiber:2.1), Food(name:'Яблоко',kcal:52,protein:.3,fat:.2,carbs:13.8,fiber:2.4), Food(name:'Греческий йогурт',kcal:73,protein:9.9,fat:2,carbs:3.9), Food(name:'Ветчина из индейки',kcal:84,protein:18,fat:2,carbs:2), Food(name:'Черника',kcal:57,protein:.7,fat:.3,carbs:14.5,fiber:2.4),
];
