import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:shared_preferences/shared_preferences.dart';

const green = Color(0xFF3D9B70);
const greenDark = Color(0xFF287451);
const mint = Color(0xFFE8F5EE);
const bg = Color(0xFFF6F8F6);
const ink = Color(0xFF17231D);
const muted = Color(0xFF7A857E);
const line = Color(0xFFE5EAE6);

class ModernFitLifeApp extends StatelessWidget {
  const ModernFitLifeApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false,
    title: 'FitLife',
    theme: ThemeData(useMaterial3: true, scaffoldBackgroundColor: bg, colorScheme: ColorScheme.fromSeed(seedColor: green)),
    home: const FitLifeHome(),
  );
}

class FoodItem {
  final String id, name;
  final double kcal, protein, fat, carbs, fiber;
  const FoodItem(this.id, this.name, this.kcal, this.protein, this.fat, this.carbs, this.fiber);
  Map<String,dynamic> toJson()=>{'id':id,'name':name,'kcal':kcal,'protein':protein,'fat':fat,'carbs':carbs,'fiber':fiber};
  factory FoodItem.fromJson(Map<String,dynamic> j)=>FoodItem(j['id'],j['name'],(j['kcal'] as num).toDouble(),(j['protein'] as num).toDouble(),(j['fat'] as num).toDouble(),(j['carbs'] as num).toDouble(),(j['fiber'] as num).toDouble());
}
class DiaryItem {
  final String id, meal, time; final FoodItem food; final double grams;
  const DiaryItem({required this.id,required this.meal,required this.food,required this.grams,required this.time});
  double get kcal=>food.kcal*grams/100; double get protein=>food.protein*grams/100; double get fat=>food.fat*grams/100; double get carbs=>food.carbs*grams/100; double get fiber=>food.fiber*grams/100;
  Map<String,dynamic> toJson()=>{'id':id,'meal':meal,'food':food.toJson(),'grams':grams,'time':time};
  factory DiaryItem.fromJson(Map<String,dynamic> j)=>DiaryItem(id:j['id'],meal:j['meal'],food:FoodItem.fromJson(Map<String,dynamic>.from(j['food'])),grams:(j['grams'] as num).toDouble(),time:j['time']);
}

const builtInFoods=<FoodItem>[
  FoodItem('egg','Яйцо',157,12.7,10.9,.7,0), FoodItem('chicken','Куриная грудка',120,22.5,2.6,0,0), FoodItem('turkey','Индейка',114,23.7,1.5,0,0), FoodItem('turkey_ham','Ветчина из индейки',84,18,2,2,0), FoodItem('beef','Говядина постная',158,26,6,0,0), FoodItem('salmon','Лосось',208,20,13,0,0), FoodItem('tuna','Тунец',116,26,.8,0,0), FoodItem('cottage','Творог 5%',121,17,5,1.8,0), FoodItem('yogurt','Греческий йогурт',73,9,2.5,3.8,0), FoodItem('skyr','Skyr',35,6,0,3,0),
  FoodItem('oats','Овсянка',366,12.3,6.1,59.5,8.3), FoodItem('buckwheat','Гречка',343,13.6,3.4,71.5,10), FoodItem('rice','Рис',344,7,.7,78,2.4), FoodItem('couscous','Кускус',376,12.8,.6,77.4,5), FoodItem('pasta','Макароны',350,12,1.5,70,3), FoodItem('potato','Картофель',82,2,.4,17,1.8), FoodItem('bread','Хлеб цельнозерновой',247,13,4.2,41,7),
  FoodItem('pepper','Перец',31,1,.3,6,2.1), FoodItem('iceberg','Айсберг',14,.9,.1,3,1.2), FoodItem('tomato','Помидор',18,.9,.2,3.9,1.2), FoodItem('cucumber','Огурец',15,.7,.1,3.6,.5), FoodItem('broccoli','Брокколи',34,2.8,.4,6.6,2.6), FoodItem('cauliflower','Цветная капуста',25,1.9,.3,5,2), FoodItem('carrot','Морковь',41,.9,.2,9.6,2.8), FoodItem('mushroom','Шампиньоны',22,3.1,.3,3.3,1),
  FoodItem('apple','Яблоко',52,.3,.2,13.8,2.4), FoodItem('banana','Банан',89,1.1,.3,22.8,2.6), FoodItem('orange','Апельсин',47,.9,.1,11.8,2.4), FoodItem('peach','Персик',39,.9,.3,9.5,1.5), FoodItem('blackberry','Ежевика',43,1.4,.5,9.6,5.3), FoodItem('blueberry','Черника',57,.7,.3,14.5,2.4),
  FoodItem('avocado','Авокадо',160,2,14.7,8.5,6.7), FoodItem('almonds','Миндаль',579,21.2,49.9,21.6,12.5), FoodItem('walnut','Грецкий орех',654,15.2,65.2,13.7,6.7), FoodItem('oil','Оливковое масло',884,0,100,0,0), FoodItem('sour_cream','Сметана 25%',248,2.6,25,3.2,0), FoodItem('ketchup','Кетчуп',110,1.2,.2,25,.7),
];

class FitLifeHome extends StatefulWidget { const FitLifeHome({super.key}); @override State<FitLifeHome> createState()=>_FitLifeHomeState(); }
class _FitLifeHomeState extends State<FitLifeHome> {
  static const kcalTarget=1900.0, proteinTarget=180.0, fatTarget=65.0, fiberTarget=30.0;
  int tab=0; double water=1.5, weight=104.2; bool loading=true;
  List<DiaryItem> diary=[]; List<FoodItem> customFoods=[]; List<String> favorites=[]; List<String> recent=[]; File? photo;
  final picker=ImagePicker();
  List<FoodItem> get foods=>[...builtInFoods,...customFoods];
  double get calories=>diary.fold(0,(s,x)=>s+x.kcal); double get protein=>diary.fold(0,(s,x)=>s+x.protein); double get fat=>diary.fold(0,(s,x)=>s+x.fat); double get carbs=>diary.fold(0,(s,x)=>s+x.carbs); double get fiber=>diary.fold(0,(s,x)=>s+x.fiber); double get left=>(kcalTarget-calories).clamp(0,kcalTarget).toDouble();
  String get key{final d=DateTime.now();return '${d.year}-${d.month.toString().padLeft(2,'0')}-${d.day.toString().padLeft(2,'0')}';}
  @override void initState(){super.initState();_load();}
  Future<void> _load() async{final p=await SharedPreferences.getInstance();final d=p.getString('diary_$key');final f=p.getString('custom_foods');if(!mounted)return;setState((){water=p.getDouble('water')??1.5;weight=p.getDouble('weight')??104.2;diary=d==null?[]:(jsonDecode(d) as List).map((e)=>DiaryItem.fromJson(Map<String,dynamic>.from(e))).toList();customFoods=f==null?[]:(jsonDecode(f) as List).map((e)=>FoodItem.fromJson(Map<String,dynamic>.from(e))).toList();favorites=p.getStringList('favorites')??[];recent=p.getStringList('recent')??[];loading=false;});}
  Future<void> _saveDiary() async{final p=await SharedPreferences.getInstance();await p.setString('diary_$key',jsonEncode(diary.map((x)=>x.toJson()).toList()));}
  Future<void> _saveLists() async{final p=await SharedPreferences.getInstance();await p.setStringList('favorites',favorites);await p.setStringList('recent',recent);}
  Future<void> _saveFoods() async{final p=await SharedPreferences.getInstance();await p.setString('custom_foods',jsonEncode(customFoods.map((x)=>x.toJson()).toList()));}
  Future<void> _num(String k,double v) async{final p=await SharedPreferences.getInstance();await p.setDouble(k,v);}
  @override Widget build(BuildContext context){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator(color:green)));final pages=<Widget>[_today(),_foodPage(),_cameraPage(),_progressPage(),_profilePage()];return Scaffold(body:SafeArea(child:IndexedStack(index:tab,children:pages)),bottomNavigationBar:NavigationBar(selectedIndex:tab,backgroundColor:Colors.white,indicatorColor:mint,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Сегодня'),NavigationDestination(icon:Icon(Icons.restaurant_outlined),selectedIcon:Icon(Icons.restaurant),label:'Питание'),NavigationDestination(icon:Icon(Icons.camera_alt_outlined),selectedIcon:Icon(Icons.camera_alt),label:'Камера'),NavigationDestination(icon:Icon(Icons.insights_outlined),selectedIcon:Icon(Icons.insights),label:'Прогресс'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Профиль')]),floatingActionButton:tab<=1?FloatingActionButton.extended(onPressed:_addFood,backgroundColor:green,foregroundColor:Colors.white,icon:const Icon(Icons.add),label:const Text('Добавить еду')):null);}

  Widget _today()=>ListView(padding:const EdgeInsets.fromLTRB(20,18,20,110),children:[_header('Сегодня',_date()),const SizedBox(height:14),_card(Row(children:[const Text('🐼',style:TextStyle(fontSize:50)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Твой помощник',style:TextStyle(color:muted)),Text(diary.isEmpty?'Панда ждёт первый приём пищи 💚':'Панда поддерживает твой ритм 💚',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:17,color:ink))]))])),const SizedBox(height:12),_dark(Row(children:[SizedBox(width:105,height:105,child:Stack(alignment:Alignment.center,children:[CircularProgressIndicator(value:(calories/kcalTarget).clamp(0,1),color:const Color(0xFF7BE0A8),backgroundColor:const Color(0x334A5A50),strokeWidth:10),Text('${left.round()}',style:const TextStyle(color:Colors.white,fontSize:24,fontWeight:FontWeight.w900))])),const SizedBox(width:16),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Дневная цель',style:TextStyle(color:Colors.white60)),Text('${calories.round()} / 1900 ккал',style:const TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.w900)),Text('Белок ${protein.round()} г · Клетчатка ${fiber.round()} г',style:const TextStyle(color:Colors.white70))]))])),const SizedBox(height:12),_card(Column(children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('Макросы',style:TextStyle(fontSize:17,fontWeight:FontWeight.w900,color:ink)),Text('Б ${protein.round()} · Ж ${fat.round()} · У ${carbs.round()}',style:const TextStyle(color:muted))]),const SizedBox(height:12),Row(children:[_bar('Белок',protein,proteinTarget),const SizedBox(width:8),_bar('Жиры',fat,fatTarget),const SizedBox(width:8),_bar('Клетчатка',fiber,fiberTarget)])])),const SizedBox(height:12),Row(children:[_stat('Вода','${water.toStringAsFixed(1)} л',Icons.water_drop_outlined,_addWater),const SizedBox(width:8),_stat('Вес','${weight.toStringAsFixed(1)} кг',Icons.monitor_weight_outlined,_addWeight),const SizedBox(width:8),_stat('Приёмов','${_grouped().length}',Icons.restaurant_outlined,null)]),const SizedBox(height:18),_next(),const SizedBox(height:18),const Text('Дневник',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900,color:ink)),const SizedBox(height:8),if(diary.isEmpty)_empty()else..._grouped().entries.map((e)=>_meal(e.key,e.value))]);

  Widget _foodPage()=>ListView(padding:const EdgeInsets.fromLTRB(20,18,20,110),children:[_header('Питание','Большая база, избранное и последние'),const SizedBox(height:12),_card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${calories.round()} ккал',style:const TextStyle(fontSize:26,fontWeight:FontWeight.w900,color:ink)),Text('Осталось ${left.round()} ккал · Б ${protein.round()} г · Ж ${fat.round()} г · Кл ${fiber.round()} г',style:const TextStyle(color:muted))])),if(recent.isNotEmpty)...[_title('Последние'),_chips(recent)],if(favorites.isNotEmpty)...[_title('Избранное'),_chips(favorites)],const SizedBox(height:8),OutlinedButton.icon(onPressed:_addCustom,icon:const Icon(Icons.add_box_outlined),label:const Text('Создать свой продукт')),const SizedBox(height:8),OutlinedButton.icon(onPressed:_addFood,icon:const Icon(Icons.search),label:const Text('Поиск продукта')),const SizedBox(height:14),..._grouped().entries.map((e)=>_meal(e.key,e.value))]);

  Widget _cameraPage()=>ListView(padding:const EdgeInsets.fromLTRB(20,18,20,30),children:[_header('Камера','Фото блюда → подтверждение'),const SizedBox(height:14),_card(Column(children:[if(photo!=null)ClipRRect(borderRadius:BorderRadius.circular(18),child:Image.file(photo!,height:240,width:double.infinity,fit:BoxFit.cover))else const Padding(padding:EdgeInsets.all(18),child:Icon(Icons.photo_camera_back_outlined,size:80,color:greenDark)),const SizedBox(height:12),Row(children:[Expanded(child:FilledButton.icon(onPressed:()=>_pick(ImageSource.camera),icon:const Icon(Icons.camera_alt),label:const Text('Камера'),style:FilledButton.styleFrom(backgroundColor:green))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:()=>_pick(ImageSource.gallery),icon:const Icon(Icons.photo_library),label:const Text('Галерея')))]),if(photo!=null)...[const SizedBox(height:14),const Align(alignment:Alignment.centerLeft,child:Text('Результат',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900,color:ink))),const SizedBox(height:6),const Align(alignment:Alignment.centerLeft,child:Text('Пока без облачного AI: фото готово для следующего шага распознавания. КБЖУ считаются только после подтверждения.',style:TextStyle(color:muted))),const SizedBox(height:10),FilledButton.icon(onPressed:_addFood,icon:const Icon(Icons.check),label:const Text('Подтвердить и выбрать продукты'),style:FilledButton.styleFrom(backgroundColor:green,minimumSize:const Size.fromHeight(50)))] ]))]);

  Widget _progressPage()=>ListView(padding:const EdgeInsets.fromLTRB(20,18,20,30),children:[_header('Прогресс','Устойчивость важнее идеального дня'),const SizedBox(height:14),_card(Column(children:[_line('Калории',calories/kcalTarget,'${calories.round()} / 1900'),_line('Белок',protein/proteinTarget,'${protein.round()} / 180 г'),_line('Жиры',fat/fatTarget,'${fat.round()} / 65 г'),_line('Клетчатка',fiber/fiberTarget,'${fiber.round()} / 30 г')]))]);
  Widget _profilePage()=>ListView(padding:const EdgeInsets.fromLTRB(20,18,20,30),children:[_header('Профиль','Цели FitLife'),const SizedBox(height:14),_card(const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('1900 ккал',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:ink)),SizedBox(height:5),Text('Белок 160–180 г · Жиры до 65 г · Клетчатка 30 г',style:TextStyle(color:muted))])),const SizedBox(height:10),_setting(Icons.restaurant,'База продуктов','${foods.length} продуктов'),_setting(Icons.camera_alt,'Камера','Камера и галерея подключены'),_setting(Icons.save,'Локальное хранение','Дневник и свои продукты сохраняются')]);

  Widget _header(String t,String s)=>Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900,color:ink)),Text(s,style:const TextStyle(color:muted))])),IconButton(onPressed:()=>setState(()=>tab=4),icon:const Icon(Icons.person_outline,color:ink))]);
  Widget _card(Widget c)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20),border:Border.all(color:line)),child:c);
  Widget _dark(Widget c)=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:const Color(0xFF203129),borderRadius:BorderRadius.circular(22)),child:c);
  Widget _bar(String l,double v,double t)=>Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(l,style:const TextStyle(fontSize:11,color:muted,fontWeight:FontWeight.w700)),const SizedBox(height:4),ClipRRect(borderRadius:BorderRadius.circular(6),child:LinearProgressIndicator(value:(v/t).clamp(0,1),minHeight:7,color:green,backgroundColor:mint))]));
  Widget _stat(String l,String v,IconData i,VoidCallback? onTap)=>Expanded(child:InkWell(onTap:onTap,child:_card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:greenDark),Text(l,style:const TextStyle(fontSize:12,color:muted)),Text(v,style:const TextStyle(fontWeight:FontWeight.w900,color:ink))]))));
  Widget _next()=>_card(ListTile(contentPadding:EdgeInsets.zero,leading:const CircleAvatar(backgroundColor:mint,child:Icon(Icons.arrow_forward,color:greenDark)),title:Text(diary.isEmpty?'Добавь первый продукт':'Следующий шаг',style:const TextStyle(fontWeight:FontWeight.w900,color:ink)),subtitle:Text(diary.isEmpty?'Белок + овощи — хороший старт':'Ориентируйся на оставшиеся калории и белок',style:const TextStyle(color:muted)),onTap:_addFood));
  Widget _empty()=>_card(const Column(children:[Icon(Icons.restaurant_menu,size:42,color:greenDark),Text('Дневник пока пуст',style:TextStyle(fontWeight:FontWeight.w900,color:ink)),Text('Добавь продукт — FitLife посчитает КБЖУ и клетчатку.',textAlign:TextAlign.center,style:TextStyle(color:muted))]));
  Widget _meal(String name,List<DiaryItem> xs)=>Padding(padding:const EdgeInsets.only(bottom:10),child:_card(Column(children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(name,style:const TextStyle(fontWeight:FontWeight.w900,color:ink)),Text('${xs.fold(0.0,(s,x)=>s+x.kcal).round()} ккал',style:const TextStyle(color:muted))]),const Divider(),...xs.map((x)=>ListTile(contentPadding:EdgeInsets.zero,onTap:()=>_edit(x),title:Text('${x.food.name} · ${x.grams.round()} г',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('Б ${x.protein.toStringAsFixed(1)} · Ж ${x.fat.toStringAsFixed(1)} · У ${x.carbs.toStringAsFixed(1)} · Кл ${x.fiber.toStringAsFixed(1)}',style:const TextStyle(color:muted)),trailing:Text('${x.kcal.round()}')))])));
  Widget _title(String s)=>Padding(padding:const EdgeInsets.only(top:10,bottom:6),child:Text(s,style:const TextStyle(fontWeight:FontWeight.w900,color:ink)));
  Widget _chips(List<String> ids)=>SizedBox(height:54,child:ListView(scrollDirection:Axis.horizontal,children:ids.map(_foodById).whereType<FoodItem>().map((f)=>Padding(padding:const EdgeInsets.only(right:8),child:ActionChip(label:Text(f.name),onPressed:()=>_addFood(preselected:f)))).toList()));
  Widget _setting(IconData i,String t,String s)=>Padding(padding:const EdgeInsets.only(bottom:8),child:_card(ListTile(contentPadding:EdgeInsets.zero,leading:CircleAvatar(backgroundColor:mint,child:Icon(i,color:greenDark)),title:Text(t,style:const TextStyle(fontWeight:FontWeight.w900,color:ink)),subtitle:Text(s,style:const TextStyle(color:muted)))));
  Widget _line(String l,double v,String s)=>ProgressLine(label:l,value:v,text:s);
  Map<String,List<DiaryItem>> _grouped(){final r=<String,List<DiaryItem>>{};for(final x in diary){r.putIfAbsent(x.meal,()=>[]).add(x);}return r;}
  FoodItem? _foodById(String id){for(final f in foods){if(f.id==id)return f;}return null;}
  String _date(){final d=DateTime.now();return '${d.day}.${d.month}.${d.year}';}

  Future<void> _pick(ImageSource source) async{final x=await picker.pickImage(source:source,imageQuality:88);if(x!=null)setState(()=>photo=File(x.path));}
  Future<void> _addFood({FoodItem? preselected}) async{FoodItem? selected=preselected;String meal='Ужин',query='';final grams=TextEditingController(text:'100');await showModalBottomSheet<void>(context:context,isScrollControlled:true,backgroundColor:bg,builder:(ctx)=>StatefulBuilder(builder:(ctx,ss){final list=foods.where((f)=>f.name.toLowerCase().contains(query.toLowerCase())).take(60).toList();return Padding(padding:EdgeInsets.fromLTRB(20,14,20,MediaQuery.of(ctx).viewInsets.bottom+20),child:Column(mainAxisSize:MainAxisSize.min,children:[Container(width:42,height:4,color:line),const SizedBox(height:12),const Text('Добавить продукт',style:TextStyle(fontSize:23,fontWeight:FontWeight.w900,color:ink)),const SizedBox(height:10),TextField(decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Поиск продукта'),onChanged:(v)=>ss(()=>query=v)),const SizedBox(height:6),SizedBox(height:230,child:ListView(children:list.map((f)=>ListTile(selected:selected?.id==f.id,selectedTileColor:mint,title:Text(f.name,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${f.kcal.round()} ккал · Б ${f.protein} · Кл ${f.fiber} / 100 г'),trailing:IconButton(icon:Icon(favorites.contains(f.id)?Icons.star:Icons.star_border),onPressed:(){ss((){favorites.contains(f.id)?favorites.remove(f.id):favorites.add(f.id);});_saveLists();}),onTap:()=>ss(()=>selected=f))).toList())),const SizedBox(height:8),Row(children:[Expanded(child:TextField(controller:grams,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Граммы'))),const SizedBox(width:8),Expanded(child:DropdownButtonFormField<String>(value:meal,items:const['Завтрак','Обед','Ужин','Перекус'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>ss(()=>meal=v??meal),decoration:const InputDecoration(labelText:'Приём')))]),const SizedBox(height:10),FilledButton.icon(onPressed:selected==null?null:(){final g=double.tryParse(grams.text.replaceAll(',','.'))??100;if(g<=0)return;final f=selected!;setState(()=>diary.add(DiaryItem(id:DateTime.now().microsecondsSinceEpoch.toString(),meal:meal,food:f,grams:g,time:TimeOfDay.now().format(ctx))));recent=[f.id,...recent.where((id)=>id!=f.id)].take(10).toList();_saveLists();_saveDiary();Navigator.pop(ctx);},icon:const Icon(Icons.check),label:const Text('Добавить'),style:FilledButton.styleFrom(backgroundColor:green,minimumSize:const Size.fromHeight(52)))]));}));}
  Future<void> _edit(DiaryItem item) async{final c=TextEditingController(text:item.grams.toStringAsFixed(0));await showDialog<void>(context:context,builder:(ctx)=>AlertDialog(title:Text(item.food.name),content:TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Граммы')),actions:[TextButton(onPressed:(){setState(()=>diary.removeWhere((x)=>x.id==item.id));_saveDiary();Navigator.pop(ctx);},child:const Text('Удалить',style:TextStyle(color:Colors.red))),FilledButton(onPressed:(){final g=double.tryParse(c.text.replaceAll(',','.'));if(g==null||g<=0)return;final i=diary.indexWhere((x)=>x.id==item.id);if(i<0)return;setState(()=>diary[i]=DiaryItem(id:item.id,meal:item.meal,food:item.food,grams:g,time:item.time));_saveDiary();Navigator.pop(ctx);},child:const Text('Сохранить'))]);}
  Future<void> _addCustom() async{final n=TextEditingController(),k=TextEditingController(),p=TextEditingController(),f=TextEditingController(),c=TextEditingController(),fi=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:const Text('Свой продукт'),content:SingleChildScrollView(child:Column(children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Название')),TextField(controller:k,decoration:const InputDecoration(labelText:'Ккал / 100 г')),TextField(controller:p,decoration:const InputDecoration(labelText:'Белок / 100 г')),TextField(controller:f,decoration:const InputDecoration(labelText:'Жиры / 100 г')),TextField(controller:c,decoration:const InputDecoration(labelText:'Углеводы / 100 г')),TextField(controller:fi,decoration:const InputDecoration(labelText:'Клетчатка / 100 г'))])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Отмена')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('Сохранить'))]));if(ok!=true||n.text.trim().isEmpty)return;setState(()=>customFoods.add(FoodItem('custom_${DateTime.now().microsecondsSinceEpoch}',n.text.trim(),double.tryParse(k.text.replaceAll(',','.'))??0,double.tryParse(p.text.replaceAll(',','.'))??0,double.tryParse(f.text.replaceAll(',','.'))??0,double.tryParse(c.text.replaceAll(',','.'))??0,double.tryParse(fi.text.replaceAll(',','.'))??0)));await _saveFoods();}
  Future<void> _addWater() async{setState(()=>water+=.25);await _num('water',water);}
  Future<void> _addWeight() async{final c=TextEditingController(text:weight.toStringAsFixed(1));final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:const Text('Вес'),content:TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(suffixText:'кг')),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Отмена')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('Сохранить'))]));if(ok!=true)return;final v=double.tryParse(c.text.replaceAll(',','.'));if(v==null||v<30||v>300)return;setState(()=>weight=v);await _num('weight',v);}
}

class ProgressLine extends StatelessWidget{final String label,text;final double value;const ProgressLine({super.key,required this.label,required this.value,required this.text});@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(bottom:15),child:Column(children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(label,style:const TextStyle(fontWeight:FontWeight.w800,color:ink)),Text(text,style:const TextStyle(color:muted))]),const SizedBox(height:6),ClipRRect(borderRadius:BorderRadius.circular(8),child:LinearProgressIndicator(value:value.clamp(0,1),minHeight:8,color:green,backgroundColor:mint))]));}
